### ISSUE TITLE
WiFi.gatewayIP() example on reference page does not correctly use code tags

### ISSUE THREAD

**Issue by per1234** [arduino-libraries/WiFi#31]
The page:
https://www.arduino.cc/en/Reference/WiFiGatewayIP

Has a some sort of markup issue that caused the code tags to not work correctly:
![clipboard01](https://user-images.githubusercontent.com/8572152/27553849-6f40a2d6-5a61-11e7-9fda-53b755368ce7.png)

Originally reported at:
http://forum.arduino.cc/index.php?topic=485918

**Comment by akash73** [comment]
fixed .
thanks!
