### ISSUE TITLE
WiFi Soft Ap web server hotspot disconnecting issue in esp8266/esp32 with redmi note 8 pro android phone

### ISSUE THREAD

**Issue by vasanth0195** [arduino-libraries/WiFi#40]
Hi there, 
I've been trying to set up an access point combined with a web server using the ESP8266WiFi/WiFi.h(for esp32) libraries for Arduino. I am using an ESP8266 NodeMCU/ESP32.

Setting up an AP using softAP works fine and connection also is stable , The problem is when trying to access the web server from a connected device, it always ends up with a timeout exception and connection not stable. but its working fine with some android but not works with redmi note 8 pro.

please give some ideas to sort this issue.

thanks in advance.

vasanth

**Comment by per1234** [comment]
Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. In fact, ESP8266 and ESP32 use a completely different library, so very much off topic for this library of the retired Arduino WiFi Shield.

This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/
