### ISSUE TITLE
Using this library for Ublox NINA W15 wifi modules

### ISSUE THREAD

**Issue by TinManAkshay** [arduino-libraries/WiFi#42]
Hi all,

I just wanted to know if this library can be used to get Ublox NINA W152 WiFi module working? If yes, what pins of NINA wifi module are required to get Wifi up and running? I'd appreciate any kind of information here.

Thanks,
Akshay

**Comment by per1234** [comment]
Hi @TinManAkshay. Thanks for your interest in this open source project.

This is the library for the long retired [Arduino WiFi Shield](https://www.arduino.cc/en/Guide/ArduinoWiFiShield), and so no longer actively supported. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to provide advice for your project over there:

https://forum.arduino.cc/
