### ISSUE TITLE
WEMOS LOLIN32 doesnt connect to WPA2 networks

### ISSUE THREAD

**Issue by elschman** [arduino-libraries/WiFi#61]
I do have a WEMOS LOLIN32 and he denied to connect to WPA2 networks.

I se all networks but the encrytion type 3 seems not to be the best idea...

13:17:13.245 -> =======================================================================
13:17:13.245 -> SSID: 'xxxnet#2'; Channel: 4; RSSI: -62; Encryption: 3
13:17:13.245 -> SSID: 'xxx.freifunk.net'; Channel: 1; RSSI: -70; Encryption: 0
13:17:13.245 -> SSID: 'xxxnet'; Channel: 1; RSSI: -70; Encryption: 3
13:17:13.245 -> SSID: 'xxxznet LoRaWan'; Channel: 11; RSSI: -79; Encryption: 3
13:17:13.245 -> SSID: 'xxxnet'; Channel: 11; RSSI: -81; Encryption: 3

If I use the freifunk wifi net it works as it should.

Is there any fw upgrade needed or other things to do ?

**Comment by per1234** [comment]
Hi @elschman. This library is for the long retired [**Arduino WiFi Shield**](https://docs.arduino.cc/retired/shields/arduino-wifi-shield). It is not used with the ESP32. The ESP32 boards platform has its own WiFi library that is used when you compile for an ESP32:

https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32

So I will close this as off topic. If you would like assistance with your project, you are welcome to post over on Arduino Forum:

https://forum.arduino.cc/
