### ISSUE TITLE
Switching between STA and AP modes on a GIGA R1 WiFi board

### ISSUE THREAD

**Issue by giorgiogallina** [arduino-libraries/WiFi#75]
Dear contributors,

I am facing some issues when switching between WiFi STA and AP mode on my Arduino GIGA R1 WIFI.
Everything seems to work fine if I execute the following code when switching between the two modes:

```
WiFi = WiFiClass(WiFiInterface::get_default_instance());
```

If I do not do so, WiFiClient and WiFiUDP won't work in STA mode when returning from AP mode.
However, it seems to me I should not be doing anything like that, so I wonder if it is at least safe.

For more details, you can follow the discussion on the Arduino forum titled [WiFiClass constructor and destructor](https://forum.arduino.cc/t/wificlass-constructor-and-destructor/1300247)

Thank you

**Comment by per1234** [comment]
Hi @giorgiogallina. This repository contains the library for the long retired [**Arduino WiFi Shield**](https://docs.arduino.cc/retired/shields/arduino-wifi-shield). Even though it has the same name, this library is completely different from the ["WiFi" library](https://github.com/arduino/ArduinoCore-mbed/tree/main/libraries/WiFi) that is used when compiling for a [**GIGA R1 WiFi**](https://docs.arduino.cc/hardware/giga-r1-wifi) board.

So I close this as off topic for this repository.
